# Generated by Django 3.1.1 on 2021-02-16 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='prescription_note',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='receival',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receival', models.CharField(choices=[('Courier', 'Courier')], default='Courier', max_length=30)),
                ('prescription_note', models.CharField(max_length=1000)),
                ('delivery_note', models.CharField(max_length=1000)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='accounts.PrescriptionItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
