# Generated by Django 3.1.1 on 2021-01-30 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('medicine_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.medicineitems')),
                ('selected_surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.selectsurgery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PrescriptionItem',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='items',
            field=models.ManyToManyField(to='accounts.PrescriptionItems'),
        ),
    ]
