# Generated by Django 3.1.1 on 2021-01-30 23:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210130_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescriptionItems',
            new_name='PrescriptionItem',
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'verbose_name': 'Prescription Item', 'verbose_name_plural': 'Prescription Items'},
        ),
    ]
