# Generated by Django 3.1.1 on 2021-02-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210211_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitallist',
            name='user',
        ),
    ]
