# Generated by Django 3.1.1 on 2021-02-16 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210216_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsurgery',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='addsurgery', to='auth.user'),
            preserve_default=False,
        ),
    ]
