# Generated by Django 3.1.1 on 2020-11-02 00:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
