# Generated by Django 3.1.1 on 2021-02-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210212_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='delivery_note',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription_note',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='receival',
            field=models.CharField(choices=[('Courier', 'Courier')], default='Courier', max_length=30),
        ),
    ]
