# Generated by Django 3.1.1 on 2020-11-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201102_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'User Addresses'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'User Infos'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mobile_no',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nhs_no',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='telephone_no',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
