# Generated by Django 3.1.1 on 2021-02-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210204_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineitems',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
