# Generated by Django 3.1.1 on 2020-11-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201102_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='county',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='house_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postcode',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(default='1', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='town',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='uk_postcode_lookup',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
