# Generated by Django 3.1.1 on 2021-02-15 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210215_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='delivery_note',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription_note',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='receival',
            field=models.CharField(choices=[('Courier', 'Courier')], default='Courier', max_length=30),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
