# Generated by Django 3.1.1 on 2020-11-09 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20201102_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=1000)),
                ('hospital', models.CharField(max_length=1000)),
                ('street', models.CharField(max_length=1000)),
                ('distirct', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=500)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitallist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
