# Generated by Django 3.1.1 on 2020-11-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hospitallist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitallist',
            name='user',
        ),
    ]
