# Generated by Django 3.1.1 on 2021-02-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_remove_medicine_user'),
        ('accounts', '0011_auto_20210206_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineitems',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine'),
        ),
        migrations.AlterField(
            model_name='medicineitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
