# Generated by Django 3.1.1 on 2020-11-09 19:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201109_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSurgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=1000)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('uk_postcode_lookup', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('address', models.CharField(max_length=2000)),
            ],
        ),
    ]
