# Generated by Django 3.1.1 on 2020-11-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_addsurgery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsurgery',
            name='user',
        ),
    ]
