# Generated by Django 3.1.1 on 2020-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201109_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsurgery',
            name='house_number',
            field=models.CharField(max_length=100),
        ),
    ]
