# Generated by Django 3.1.1 on 2020-11-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201109_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsurgery',
            name='house_number',
        ),
    ]
