# Generated by Django 3.1.1 on 2020-11-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_addsurgery_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsurgery',
            name='house_number',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='house_number',
            field=models.CharField(max_length=1000),
        ),
    ]
