# Generated by Django 3.1.1 on 2020-11-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201109_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsurgery',
            name='house_number',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nhs_no',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(max_length=1000),
        ),
    ]
