# Generated by Django 3.1.1 on 2020-11-09 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0026_auto_20201109_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('middle_names', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('landline_telephone_no', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('nhs_no', models.CharField(max_length=10000)),
                ('notes', models.TextField(max_length=100000)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street', models.CharField(max_length=2000)),
                ('town', models.CharField(max_length=1000)),
                ('county', models.CharField(max_length=1000)),
                ('postcode', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
