# Generated by Django 3.1.1 on 2020-11-23 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0032_auto_20201116_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsurgery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addsurgery', to=settings.AUTH_USER_MODEL),
        ),
    ]
