# Generated by Django 3.1.1 on 2020-11-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20201123_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addsurgery',
            options={'verbose_name': 'Add Surgery', 'verbose_name_plural': 'Add Surgeries'},
        ),
    ]
