# Generated by Django 3.1.1 on 2020-12-16 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicines', '0003_auto_20201031_1202'),
        ('accounts', '0036_prescriptionitem_selectsurgery'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='hospital',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='accounts.hospitallist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='medicines.medicine'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='accounts.PrescriptionItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
