# Generated by Django 3.1.1 on 2020-12-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20201031_1202'),
        ('accounts', '0037_auto_20201217_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionitem',
            old_name='order_quantity',
            new_name='prescription_quantity',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='order_item',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription_item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='medicines.medicine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='accounts.hospitallist'),
        ),
    ]
