# Generated by Django 3.1.1 on 2021-01-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_hospitallist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='items',
            field=models.ManyToManyField(null=True, to='accounts.PrescriptionItem'),
        ),
    ]
