# Generated by Django 3.1.1 on 2021-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210105_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionitem',
            old_name='hospital',
            new_name='surgery',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='items',
            field=models.ManyToManyField(to='accounts.PrescriptionItem'),
        ),
    ]
