# Generated by Django 3.1.1 on 2021-01-13 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20201031_1202'),
        ('accounts', '0041_auto_20210111_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='medicines.medicine')),
            ],
        ),
    ]
