# Generated by Django 3.1.1 on 2021-01-13 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0042_medicineitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineitems',
            options={'verbose_name': 'Medicine Item', 'verbose_name_plural': 'Medicine Items'},
        ),
        migrations.AddField(
            model_name='medicineitems',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to=settings.AUTH_USER_MODEL),
        ),
    ]
