# Generated by Django 3.1.1 on 2021-01-13 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20201031_1202'),
        ('accounts', '0043_auto_20210113_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine'),
        ),
    ]
