# Generated by Django 3.1.1 on 2021-01-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20210113_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineitems',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
