# Generated by Django 3.1.1 on 2021-01-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20201031_1202'),
        ('accounts', '0048_auto_20210114_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicineitems', to='medicines.medicine'),
        ),
    ]
