# Generated by Django 3.1.1 on 2021-01-23 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0051_auto_20210123_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectsurgery',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectsurgery', to=settings.AUTH_USER_MODEL),
        ),
    ]
