# Generated by Django 3.1.1 on 2021-01-23 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0052_auto_20210123_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineitems',
            name='user',
        ),
        migrations.AddField(
            model_name='medicineitems',
            name='user',
            field=models.ManyToManyField(related_name='medicineitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
