# Generated by Django 3.1.1 on 2021-01-25 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20201031_1202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0060_auto_20210125_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicineitems', to='medicines.medicine'),
        ),
        migrations.AlterField(
            model_name='medicineitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
