# Generated by Django 3.1.1 on 2021-01-25 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0062_auto_20210125_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsurgery',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addsurgery', to=settings.AUTH_USER_MODEL),
        ),
    ]
